<template>
    <div>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
      <p>Switch的文档</p>
    </div>
</template>

<script lang="ts">
export default {

}
</script>

<style lang="scss" scoped>

</style>